version: '3'
services:
  front:
    build: ./docker/front
    volumes:
      - ./front:/var/www/html/
    working_dir: /var/www/html
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - HOST=0.0.0.0
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  api:
    build: ./docker/api
    volumes:
      - ./api:/go/src/project
  nginx:
    build: ./docker/nginx
    ports:
      - '1234:1234'
