version: '3'
services:
  rp:
    build: ./docker/rp
    ports:
      - '1234:1234'
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    depends_on:
      - 'rp'
  api:
    build: ./docker/api
    volumes:
      - ./api:/go/src/api
    depends_on:
      - 'db'
  front:
    build: ./docker/front
    volumes:
      - ./front:/var/www/html/
    working_dir: /var/www/html
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - HOST=0.0.0.0
    depends_on:
      - 'api'
